spring.application.name=spring-and-spring-boot
server.port=8080
server.error.include-message=always

spring.h2.console.enabled=true

spring.datasource.url = jdbc:h2:mem:ludeesha'sdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver